---
openapi: 3.0.1
info:
  title: Student Mentor Appointment API V1
  version: v1
paths:
  "/appointments":
    post:
      summary: create appointment
      tags:
        - appointments
      consumes:
        - application/json
      parameters:
        - in: body
          name: appointment
          description: The appointment to create.
          schema:
            type: object
            properties:
              mentor_id:
                type: integer
              start_date:
                type: string
              call_reason:
                type: string
            required:
              - mentor_id
              - start_date
      responses:
        '201':
          description: created
        '401':
          description: unauthorized
        '422':
          description: missing params
    get:
      summary: list appointments
      tags:
        - appointments
      parameters:
        - in: query
          name: between.lower_bound
          schema:
            type: string
          description: lower bound to filter appointents
        - in: query
          name: between.upper_bound
          schema:
            type: string
          description: upper bound to filter appointents
      responses:
        '200':
          description: successful
  "/mentors":
    post:
      summary: create mentor
      tags:
        - mentors
      consumes:
        - application/json
      parameters:
        - in: body
          name: mentor
          description: The mentor to create.
          schema:
            type: object
            required:
              - first_name
              - last_name
              - email
              - password
            properties:
              first_name:
                type: string
              last_name:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        '201':
          description: created
        '422':
          description: missing params
    get:
      summary: list mentors
      tags:
        - mentors
      responses:
        '200':
          description: successful
  "/mentors/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: mentor mentor
      tags:
        - mentors
      responses:
        '200':
          description: successful
  "/mentors/{id}/agenda":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: agenda mentor
      tags:
        - mentors
      responses:
        '200':
          description: successful
  "/mentors/me":
    get:
      summary: me mentor
      tags:
        - mentors
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/mentor-login":
    post:
      summary: login mentor
      tags:
        - mentors
      responses:
        '200':
          description: successful
        '422':
          description: missing params
  "/students":
    post:
      summary: create student
      tags:
        - students
      consumes:
        - application/json
      parameters:
        - in: body
          name: student
          description: The mentor to create.
          schema:
            type: object
            required:
              - first_name
              - last_name
              - email
              - password
            properties:
              first_name:
                type: string
              last_name:
                type: string
              email:
                type: string
                default: foo@bar.com
              password:
                type: string
              time_zone:
                type: string
                default: UTC
      responses:
        '200':
          description: successful
        '422':
          description: missing params
    get:
      summary: list students
      tags:
        - students
      responses:
        '200':
          description: successful
  "/students/me":
    get:
      summary: me student
      tags:
        - students
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/students/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
    get:
      summary: student student
      tags:
        - students
      responses:
        '200':
          description: successful
        '404':
          description: wrong id
  "/students/{id}/appointments":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
    get:
      summary: appointments student
      tags:
        - students
      responses:
        '200':
          description: successful
        '404':
          description: wrong id
  "/login":
    post:
      summary: login student
      tags:
        - students
      responses:
        '200':
          description: successful
servers:
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
