---
openapi: 3.0.1
info:
  title: Student Mentor Appointment API V1
  version: v1
paths:
  "/appointments":
    post:
      summary: create appointment
      security:
        - Bearer: [ ]
      tags:
        - appointments
      consumes:
        - application/json
      requestBody:
        description: Appointment object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                appointment:
                  type: object
                  required:
                    - mentor_id
                    - start_date
                  properties:
                    mentor_id:
                      type: integer
                    start_date:
                      type: string
                      format: date-time
                    call_reason:
                      type: string
      responses:
        '201':
          description: created
        '401':
          description: unauthorized
        '422':
          description: missing params
    get:
      summary: list appointments
      tags:
        - appointments
      parameters:
        - in: query
          name: lower_bound
          schema:
            type: string
            format: date-time
          description: lower bound to filter appointents (exp = 2021-05-10T12:43:45.092Z)
        - in: query
          name: upper_bound
          schema:
            type: string
            format: date-time
          description: upper bound to filter appointents (exp = 2021-05-10T14:43:45.092Z)
      responses:
        '200':
          description: successful
  "/mentors":
    post:
      summary: create mentor
      tags:
        - mentors
      consumes:
        - application/json
      requestBody:
        description: Mentor object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mentor:
                  type: object
                  required:
                    - first_name
                    - last_name
                    - email
                    - password
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                    time_zone:
                      type: string
                      default: UTC
      responses:
        '201':
          description: created
        '422':
          description: missing params
    get:
      summary: list mentors
      tags:
        - mentors
      responses:
        '200':
          description: successful
  "/mentors/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: mentor mentor
      tags:
        - mentors
      responses:
        '200':
          description: successful
  "/mentors/{id}/agenda":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: agenda mentor
      tags:
        - mentors
      responses:
        '200':
          description: successful
  "/mentors/me":
    get:
      summary: me mentor
      tags:
        - mentors
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/mentor-login":
    post:
      summary: login mentor
      tags:
        - mentors
      consumes:
        - application/json
      requestBody:
        description: Mentor object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: successful
        '422':
          description: missing params
  "/students":
    post:
      summary: create student
      tags:
        - students
      consumes:
        - application/json
      requestBody:
        description: Student object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                student:
                  type: object
                  required:
                    - first_name
                    - last_name
                    - email
                    - password
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                    time_zone:
                      type: string
                      default: UTC
      responses:
        '200':
          description: successful
        '422':
          description: missing params
    get:
      summary: list students
      tags:
        - students
      responses:
        '200':
          description: successful
  "/students/me":
    get:
      summary: me student
      tags:
        - students
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/students/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
    get:
      summary: student student
      tags:
        - students
      responses:
        '200':
          description: successful
        '404':
          description: wrong id
  "/students/{id}/appointments":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
    get:
      summary: appointments student
      tags:
        - students
      responses:
        '200':
          description: successful
        '404':
          description: wrong id
  "/login":
    post:
      summary: login student
      tags:
        - students
      requestBody:
        description: Student object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: successful
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
